/** Planner types, localStorage persistence, and pure manifest helpers. */

export type DayName = "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday";
export type TaskStatus = "work" | "holiday" | "sick" | "pto" | "personal" | "offsite";
export type PlannerTab = "daily" | "weekly" | "monthly" | "templates" | "tracker" | "goals" | "reviews";
export type TemplateCadence = "daily" | "weekly" | "monthly" | "interval";
export type TrackerStatus = "Complete" | "Coming Up" | "Pending";

export type DayEntry = {
  status: TaskStatus;
  planned?: string;
  did?: string;
  label?: string;
  plannedAutoGenerated?: boolean;
  plannedTemplateIds?: string[];
  trackerSourceType?: "holiday" | "pto" | "conference" | "trip";
  trackerSourceId?: string;
  officeTripBanner?: string;
  officeTripEventId?: string;
};

export type WeekEntry = Partial<Record<DayName, DayEntry>>;
export type WeeklyReviewEntry = { content: string };
export type MonthlyReviewEntry = { content: string; achievements?: string; date_completed?: string };
export type MonthEntry = {
  daily_logs: Record<string, WeekEntry>;
  weekly_reviews: Record<string, WeeklyReviewEntry>;
  monthly_review: MonthlyReviewEntry;
};
export type YearEntry = Record<string, MonthEntry>;
export type PublicHolidayEntry = {
  id: string;
  name: string;
  date: string;
  status: TrackerStatus;
  notes: string;
};
export type PtoEntry = {
  id: string;
  description: string;
  startDate: string;
  endDate: string;
  daysTotal: number;
  daysTaken: number;
  status: TrackerStatus;
  notes: string;
};
export type ConferenceEntry = {
  id: string;
  eventName: string;
  startDate: string;
  endDate: string;
  location: string;
  activity: "Booked" | "Pending";
  status: TrackerStatus;
  notes: string;
};
export type OfficeTripEntry = {
  id: string;
  tripName: string;
  startDate: string;
  endDate: string;
  location: string;
  activity: "Booked" | "Pending";
  status: TrackerStatus;
  notes: string;
};
export type TrackerData = {
  public_holidays: PublicHolidayEntry[];
  pto: PtoEntry[];
  conferences: ConferenceEntry[];
  office_trips: OfficeTripEntry[];
  pto_stats: {
    total_allocation: number;
  };
};
export type TaskManifest = {
  tracker?: TrackerData;
  [year: string]: YearEntry | TrackerData | undefined;
};
export type PlanTemplate = {
  id: string;
  name: string;
  cadence: TemplateCadence;
  intervalDays: number;
  startDate: string;
  content: string;
  enabled: boolean;
  recurrenceDay: DayName;
};
export type PlannerLayoutTemplates = {
  dailyPrimaryLabel: string;
  dailySecondaryEnabled: boolean;
  dailySecondaryLabel: string;
  weeklyLeftHeader: string;
  weeklyRightHeader: string;
  weeklyDefaultContent: string;
  monthlyLeftHeader: string;
  monthlyRightHeader: string;
  monthlyPrompts: string[];
};

const STORAGE_KEY = "metis_daily_task_view_v1";
const TEMPLATE_STORAGE_KEY = "metis_daily_task_templates_v1";
const LAYOUT_TEMPLATE_STORAGE_KEY = "metis_planner_layout_templates_v1";
const GOALS_STORAGE_KEY = "metis_planner_goals_v1";
const REVIEWS_STORAGE_KEY = "metis_planner_reviews_v1";

export type GoalSection = {
  id: string;
  title: string;
  content: string;
};

const DEFAULT_REVIEW_HEADERS = [
  "Review Cycle",
  "Manager Review - Strengths",
  "Manager Review - Areas of Opportunity",
  "Personal Review - Strengths",
  "Personal Review - Areas of Opportunity",
] as const;

export type ReviewTableRow = {
  id: string;
  cycleLabel: string;
  managerStrengths: string;
  managerOpportunity: string;
  personalStrengths: string;
  personalOpportunity: string;
};

export type ReviewsTableState = {
  headers: [string, string, string, string, string];
  rows: ReviewTableRow[];
};
export const TEMPLATE_FUTURE_HORIZON_DAYS = 365;
export const DAY_NAMES: DayName[] = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
const MONTH_INDEX: Record<string, number> = {
  January: 0,
  February: 1,
  March: 2,
  April: 3,
  May: 4,
  June: 5,
  July: 6,
  August: 7,
  September: 8,
  October: 9,
  November: 10,
  December: 11,
};
const DAY_INDEX: Record<DayName, number> = {
  Monday: 0,
  Tuesday: 1,
  Wednesday: 2,
  Thursday: 3,
  Friday: 4,
};
export const MONTHLY_PROMPTS = [
  "What went well?",
  "What went badly?",
  "What did you struggle with?",
  "What did you learn?",
  "Action points from the previous month - what am I going to do differently / focus on.",
];
export const HOLIDAY_COUNTRIES: Array<{ code: string; label: string }> = [
  { code: "US", label: "United States" },
  { code: "CA", label: "Canada" },
  { code: "GB", label: "United Kingdom" },
  { code: "AU", label: "Australia" },
  { code: "DE", label: "Germany" },
  { code: "FR", label: "France" },
  { code: "IN", label: "India" },
  { code: "JP", label: "Japan" },
];
export const HOLIDAY_REGIONS: Record<string, Array<{ code: string; label: string }>> = {
  US: [
    { code: "US-CA", label: "California" },
    { code: "US-NY", label: "New York" },
    { code: "US-TX", label: "Texas" },
    { code: "US-WA", label: "Washington" },
  ],
  CA: [
    { code: "CA-ON", label: "Ontario" },
    { code: "CA-QC", label: "Quebec" },
    { code: "CA-BC", label: "British Columbia" },
    { code: "CA-AB", label: "Alberta" },
  ],
  AU: [
    { code: "AU-NSW", label: "New South Wales" },
    { code: "AU-VIC", label: "Victoria" },
    { code: "AU-QLD", label: "Queensland" },
    { code: "AU-WA", label: "Western Australia" },
  ],
  DE: [
    { code: "DE-BY", label: "Bavaria" },
    { code: "DE-BW", label: "Baden-Wuerttemberg" },
    { code: "DE-NW", label: "North Rhine-Westphalia" },
  ],
};
export const WEEKLY_TEMPLATE = "- \n\n**Action Points:** ";
export const DEFAULT_LAYOUT_TEMPLATES: PlannerLayoutTemplates = {
  dailyPrimaryLabel: "What do I want to do",
  dailySecondaryEnabled: true,
  dailySecondaryLabel: "What did I do",
  weeklyLeftHeader: "Encountered Weekly",
  weeklyRightHeader: "Main Points & Issues Encountered",
  weeklyDefaultContent: WEEKLY_TEMPLATE,
  monthlyLeftHeader: "Monthly Review",
  monthlyRightHeader: "Issues Encountered",
  monthlyPrompts: [...MONTHLY_PROMPTS],
};
export const SPECIAL_LABELS: Record<Exclude<TaskStatus, "work">, string> = {
  holiday: "Public Holiday",
  sick: "Sick Day",
  pto: "PTO",
  personal: "Personal",
  offsite: "Off-site / Conference",
};

export const PLANNER_PURPLE_HEADER =
  "flex min-h-[2.5rem] items-center justify-center rounded-md bg-[#7F00FF] px-2 py-1.5 text-center text-[11px] font-semibold text-white";

export function debounceLocalStorage(key: string, value: unknown, delayMs = 350) {
  const store = debounceLocalStorage as typeof debounceLocalStorage & {
    _timers?: Map<string, ReturnType<typeof setTimeout>>;
  };
  if (!store._timers) store._timers = new Map();
  const prev = store._timers.get(key);
  if (prev) clearTimeout(prev);
  store._timers.set(
    key,
    setTimeout(() => {
      localStorage.setItem(key, JSON.stringify(value));
      store._timers?.delete(key);
    }, delayMs),
  );
}

export function makeMonthlyTemplateContent(prompts: string[] = MONTHLY_PROMPTS): string {
  return prompts.map((prompt) => `- ${prompt}\n`).join("\n");
}

export function makeEmptyMonthEntry(): MonthEntry {
  return {
    daily_logs: {},
    weekly_reviews: {},
    monthly_review: { content: "", achievements: "" },
  };
}

export function makeEmptyTracker(): TrackerData {
  return {
    public_holidays: [],
    pto: [],
    conferences: [],
    office_trips: [],
    pto_stats: { total_allocation: 26 },
  };
}

export function loadManifest(): TaskManifest {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return {};
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    const normalized: TaskManifest = {};

    for (const [year, months] of Object.entries(parsed ?? {})) {
      if (year === "tracker") {
        const source = (months ?? {}) as Partial<TrackerData>;
        const publicHolidays = Array.isArray(source.public_holidays) ? source.public_holidays as PublicHolidayEntry[] : [];
        const pto = Array.isArray(source.pto) ? source.pto as Array<Partial<PtoEntry> & { startDate?: string; endDate?: string }> : [];
        const conferences = Array.isArray(source.conferences)
          ? source.conferences as Array<Partial<ConferenceEntry> & { date?: string; startDate?: string; endDate?: string }>
          : [];
        const officeTrips = Array.isArray(source.office_trips)
          ? source.office_trips as Array<Partial<OfficeTripEntry> & { date?: string; startDate?: string; endDate?: string }>
          : [];
        normalized.tracker = {
          public_holidays: publicHolidays,
          pto: pto.map((row) => ({
            id: row.id ?? makeRowId(),
            description: row.description ?? "",
            startDate: row.startDate ?? toIsoDate(new Date()),
            endDate: row.endDate ?? row.startDate ?? toIsoDate(new Date()),
            daysTotal: Math.max(1, Number(row.daysTotal) || 1),
            daysTaken: Math.max(0, Number(row.daysTaken) || 0),
            status: row.status ?? "Coming Up",
            notes: row.notes ?? "",
          })),
          conferences: conferences.map((row) => ({
            id: row.id ?? makeRowId(),
            eventName: row.eventName ?? "",
            startDate: row.startDate ?? row.date ?? toIsoDate(new Date()),
            endDate: row.endDate ?? row.startDate ?? row.date ?? toIsoDate(new Date()),
            location: row.location ?? "",
            activity: row.activity === "Booked" ? "Booked" : "Pending",
            status: row.status ?? "Coming Up",
            notes: row.notes ?? "",
          })),
          office_trips: officeTrips.map((row) => ({
            id: row.id ?? makeRowId(),
            tripName: row.tripName ?? "",
            startDate: row.startDate ?? row.date ?? toIsoDate(new Date()),
            endDate: row.endDate ?? row.startDate ?? row.date ?? toIsoDate(new Date()),
            location: row.location ?? "",
            activity: row.activity === "Booked" ? "Booked" : "Pending",
            status: row.status ?? "Coming Up",
            notes: row.notes ?? "",
          })),
          pto_stats: {
            total_allocation:
              typeof source.pto_stats?.total_allocation === "number"
                ? source.pto_stats.total_allocation
                : 26,
          },
        };
        continue;
      }
      normalized[year] = {};
      for (const [month, maybeMonthEntry] of Object.entries((months as Record<string, unknown>) ?? {})) {
        const source = (maybeMonthEntry ?? {}) as Record<string, unknown>;
        const hasNormalizedShape =
          typeof source.daily_logs === "object" &&
          source.daily_logs !== null &&
          typeof source.weekly_reviews === "object" &&
          source.weekly_reviews !== null &&
          typeof source.monthly_review === "object" &&
          source.monthly_review !== null;

        if (hasNormalizedShape) {
          const monthlyReview = source.monthly_review as Record<string, unknown>;
          normalized[year][month] = {
            daily_logs: source.daily_logs as Record<string, WeekEntry>,
            weekly_reviews: source.weekly_reviews as Record<string, WeeklyReviewEntry>,
            monthly_review: {
              content:
                typeof monthlyReview.content === "string"
                  ? monthlyReview.content
                  : "",
              achievements:
                typeof monthlyReview.achievements === "string"
                  ? monthlyReview.achievements
                  : "",
              date_completed:
                typeof monthlyReview.date_completed === "string"
                  ? monthlyReview.date_completed
                  : undefined,
            },
          };
          continue;
        }

        // Backward compatibility: old versions stored week keys directly under month.
        const migrated = makeEmptyMonthEntry();
        for (const [wk, wkEntry] of Object.entries(source)) {
          if (!wk.startsWith("week_")) continue;
          migrated.daily_logs[wk] = wkEntry as WeekEntry;
        }
        normalized[year][month] = migrated;
      }
    }

    return normalized;
  } catch {
    return {};
  }
}

export function saveManifest(manifest: TaskManifest) {
  debounceLocalStorage(STORAGE_KEY, manifest);
}

export function isDayName(value: unknown): value is DayName {
  return value === "Monday" || value === "Tuesday" || value === "Wednesday" || value === "Thursday" || value === "Friday";
}

export function jsDayFromDayName(day: DayName): number {
  return DAY_INDEX[day] + 1; // Monday->1 ... Friday->5
}

export function loadTemplates(): PlanTemplate[] {
  try {
    const raw = localStorage.getItem(TEMPLATE_STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as unknown;
    if (!Array.isArray(parsed)) return [];
    return parsed
      .map((item) => {
        const t = item as Partial<PlanTemplate>;
        if (!t || typeof t.content !== "string" || typeof t.startDate !== "string") return null;
        const cadence: TemplateCadence =
          t.cadence === "weekly" || t.cadence === "monthly" || t.cadence === "interval"
            ? t.cadence
            : "daily";
        return {
          id: typeof t.id === "string" ? t.id : `${Date.now()}-${Math.random().toString(36).slice(2)}`,
          name: typeof t.name === "string" ? t.name : "Template",
          cadence,
          intervalDays:
            typeof t.intervalDays === "number" && Number.isFinite(t.intervalDays) && t.intervalDays > 0
              ? Math.floor(t.intervalDays)
              : 1,
          startDate: t.startDate,
          content: t.content,
          enabled: t.enabled !== false,
          recurrenceDay: isDayName(t.recurrenceDay)
            ? t.recurrenceDay
            : (dayNameFromDate(parseIsoDateLocal(t.startDate) ?? new Date()) ?? "Monday"),
        };
      })
      .filter((t): t is PlanTemplate => Boolean(t));
  } catch {
    return [];
  }
}

export function saveTemplates(templates: PlanTemplate[]) {
  localStorage.setItem(TEMPLATE_STORAGE_KEY, JSON.stringify(templates, null, 2));
}

export function loadLayoutTemplates(): PlannerLayoutTemplates {
  try {
    const raw = localStorage.getItem(LAYOUT_TEMPLATE_STORAGE_KEY);
    if (!raw) return DEFAULT_LAYOUT_TEMPLATES;
    const parsed = JSON.parse(raw) as Partial<PlannerLayoutTemplates>;
    const monthlyPrompts = Array.isArray(parsed.monthlyPrompts)
      ? parsed.monthlyPrompts
          .map((p) => (typeof p === "string" ? p.trim() : ""))
          .filter((p) => p.length > 0)
      : [];
    return {
      dailyPrimaryLabel: (parsed.dailyPrimaryLabel ?? DEFAULT_LAYOUT_TEMPLATES.dailyPrimaryLabel).trim() || DEFAULT_LAYOUT_TEMPLATES.dailyPrimaryLabel,
      dailySecondaryEnabled: parsed.dailySecondaryEnabled ?? DEFAULT_LAYOUT_TEMPLATES.dailySecondaryEnabled,
      dailySecondaryLabel: (parsed.dailySecondaryLabel ?? DEFAULT_LAYOUT_TEMPLATES.dailySecondaryLabel).trim() || DEFAULT_LAYOUT_TEMPLATES.dailySecondaryLabel,
      weeklyLeftHeader: (parsed.weeklyLeftHeader ?? DEFAULT_LAYOUT_TEMPLATES.weeklyLeftHeader).trim() || DEFAULT_LAYOUT_TEMPLATES.weeklyLeftHeader,
      weeklyRightHeader: (parsed.weeklyRightHeader ?? DEFAULT_LAYOUT_TEMPLATES.weeklyRightHeader).trim() || DEFAULT_LAYOUT_TEMPLATES.weeklyRightHeader,
      weeklyDefaultContent: parsed.weeklyDefaultContent ?? DEFAULT_LAYOUT_TEMPLATES.weeklyDefaultContent,
      monthlyLeftHeader: (parsed.monthlyLeftHeader ?? DEFAULT_LAYOUT_TEMPLATES.monthlyLeftHeader).trim() || DEFAULT_LAYOUT_TEMPLATES.monthlyLeftHeader,
      monthlyRightHeader: (parsed.monthlyRightHeader ?? DEFAULT_LAYOUT_TEMPLATES.monthlyRightHeader).trim() || DEFAULT_LAYOUT_TEMPLATES.monthlyRightHeader,
      monthlyPrompts: monthlyPrompts.length ? monthlyPrompts : [...DEFAULT_LAYOUT_TEMPLATES.monthlyPrompts],
    };
  } catch {
    return DEFAULT_LAYOUT_TEMPLATES;
  }
}

export function saveLayoutTemplates(layout: PlannerLayoutTemplates) {
  localStorage.setItem(LAYOUT_TEMPLATE_STORAGE_KEY, JSON.stringify(layout, null, 2));
}

export function startOfWeekMonday(d: Date): Date {
  const out = new Date(d);
  out.setHours(0, 0, 0, 0);
  const day = out.getDay(); // 0 Sun .. 6 Sat
  const delta = day === 0 ? -6 : 1 - day;
  out.setDate(out.getDate() + delta);
  return out;
}

export function addDays(d: Date, n: number): Date {
  const out = new Date(d);
  out.setDate(out.getDate() + n);
  return out;
}

export function startOfDay(d: Date): Date {
  const out = new Date(d);
  out.setHours(0, 0, 0, 0);
  return out;
}

export function monthName(d: Date): string {
  return d.toLocaleString("en-US", { month: "long" });
}

export function monthShort(d: Date): string {
  return d.toLocaleString("en-US", { month: "short" });
}

export function weekKey(monday: Date): string {
  const friday = addDays(monday, 4);
  return `week_${String(monday.getDate()).padStart(2, "0")}_${String(friday.getDate()).padStart(2, "0")}`;
}

/** Parse `${weekKey}_${DayName}` from Daily Log expanded-cell state. */
export function parseDailyExpandedFocus(key: string | null): { wk: string; day: DayName } | null {
  if (!key) return null;
  for (const d of DAY_NAMES) {
    const suf = `_${d}`;
    if (key.endsWith(suf)) {
      return { wk: key.slice(0, -suf.length), day: d };
    }
  }
  return null;
}

export function weekHeader(monday: Date): string {
  const friday = addDays(monday, 4);
  const sameMonth = monday.getMonth() === friday.getMonth();
  if (sameMonth) {
    return `${monday.getDate()} - ${friday.getDate()} ${monthShort(monday)}`;
  }
  return `${monday.getDate()} ${monthShort(monday)} - ${friday.getDate()} ${monthShort(friday)}`;
}

export function parseWeekStartFromKey(year: number, monthIndex: number, wk: string): Date | null {
  const m = /^week_(\d{2})_(\d{2})$/.exec(wk);
  if (!m) return null;
  const day = Number(m[1]);
  const d = new Date(year, monthIndex, day);
  if (Number.isNaN(d.getTime())) return null;
  return startOfWeekMonday(d);
}

/** Calendar month selected in Weekly Review navigation (the week containing the 1st). */
export function resolveWeeklyViewMonth(anchorWeek: Date): Date {
  const weekStart = startOfDay(anchorWeek);
  const weekEnd = addDays(weekStart, 6);
  for (let y = weekStart.getFullYear() - 1; y <= weekStart.getFullYear() + 1; y++) {
    for (let m = 0; m < 12; m++) {
      const first = monthStart(y, m);
      if (first.getTime() >= weekStart.getTime() && first.getTime() <= weekEnd.getTime()) {
        return first;
      }
    }
  }
  return monthStart(anchorWeek.getFullYear(), anchorWeek.getMonth());
}

/** Every Monday that falls inside the given calendar month. */
export function mondaysInCalendarMonth(year: number, monthIndex: number): Date[] {
  const result: Date[] = [];
  const first = monthStart(year, monthIndex);
  let monday = startOfWeekMonday(first);
  if (monday.getTime() < first.getTime()) {
    monday = addDays(monday, 7);
  }
  while (monday.getFullYear() === year && monday.getMonth() === monthIndex) {
    result.push(new Date(monday));
    monday = addDays(monday, 7);
  }
  return result;
}

export function toIsoDate(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

export function parseIsoDateLocal(value: string): Date | null {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
  if (!m) return null;
  const year = Number(m[1]);
  const monthIdx = Number(m[2]) - 1;
  const day = Number(m[3]);
  const d = new Date(year, monthIdx, day);
  d.setHours(0, 0, 0, 0);
  if (d.getFullYear() !== year || d.getMonth() !== monthIdx || d.getDate() !== day) {
    return null;
  }
  return d;
}

export function normalizeDateRange(startIso: string, endIso: string): { start: Date; end: Date } | null {
  const start = parseIsoDateLocal(startIso);
  const end = parseIsoDateLocal(endIso);
  if (!start || !end) return null;
  if (start.getTime() <= end.getTime()) return { start, end };
  return { start: end, end: start };
}

export function eachDateInclusive(startIso: string, endIso: string, fn: (d: Date) => void) {
  const range = normalizeDateRange(startIso, endIso);
  if (!range) return;
  let cursor = startOfDay(range.start);
  const end = startOfDay(range.end);
  while (cursor.getTime() <= end.getTime()) {
    fn(cursor);
    cursor = addDays(cursor, 1);
  }
}

export function lastFridayOfMonth(anchor: Date): Date {
  const year = anchor.getFullYear();
  const month = anchor.getMonth();
  const d = new Date(year, month + 1, 0);
  d.setHours(0, 0, 0, 0);
  while (d.getDay() !== 5) {
    d.setDate(d.getDate() - 1);
  }
  return d;
}

export function monthStart(year: number, monthIndex: number): Date {
  const d = new Date(year, monthIndex, 1);
  d.setHours(0, 0, 0, 0);
  return d;
}

export function getYearEntry(manifest: TaskManifest, year: string): YearEntry {
  const value = manifest[year];
  if (!value || typeof value !== "object" || Array.isArray(value) || year === "tracker") return {};
  if ("public_holidays" in (value as object)) return {};
  return value as YearEntry;
}

export function getTracker(manifest: TaskManifest): TrackerData {
  return manifest.tracker ?? makeEmptyTracker();
}

export function monthEntryFor(manifest: TaskManifest, monday: Date): MonthEntry {
  const year = String(monday.getFullYear());
  const month = monthName(monday);
  return getYearEntry(manifest, year)[month] ?? makeEmptyMonthEntry();
}

export function dayDate(monday: Date, day: DayName): Date {
  return addDays(monday, DAY_INDEX[day]);
}

export function dayNameFromDate(date: Date): DayName | null {
  const day = date.getDay();
  if (day === 1) return "Monday";
  if (day === 2) return "Tuesday";
  if (day === 3) return "Wednesday";
  if (day === 4) return "Thursday";
  if (day === 5) return "Friday";
  return null;
}

export function mondayForDate(date: Date): Date {
  return startOfWeekMonday(date);
}

export function nextWeekdayOnOrAfter(date: Date, day: DayName): Date {
  const out = startOfDay(date);
  const target = jsDayFromDayName(day);
  const delta = (target - out.getDay() + 7) % 7;
  return addDays(out, delta);
}

export function weekdayOccurrenceInMonth(date: Date): number {
  return Math.floor((date.getDate() - 1) / 7) + 1;
}

export function recurrenceLabel(t: PlanTemplate): string {
  if (t.cadence === "daily") return "daily";
  if (t.cadence === "weekly") return `every ${t.recurrenceDay}`;
  if (t.cadence === "monthly") return `monthly on ${t.recurrenceDay}`;
  return `every ${t.intervalDays} days on ${t.recurrenceDay}`;
}

export function matchingTemplatesForDate(date: Date, templates: PlanTemplate[]): PlanTemplate[] {
  return templates.filter((t) => matchesTemplateOnDate(t, date) && t.content.trim().length > 0);
}

export function makeRowId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

export function defaultGoalSections(): GoalSection[] {
  return [
    { id: makeRowId(), title: "Business related", content: "" },
    { id: makeRowId(), title: "Self-Improvement", content: "" },
  ];
}

export function loadGoals(): GoalSection[] {
  try {
    const raw = localStorage.getItem(GOALS_STORAGE_KEY);
    if (!raw) return defaultGoalSections();
    const parsed = JSON.parse(raw) as unknown;
    if (!Array.isArray(parsed)) return defaultGoalSections();
    if (parsed.length === 0) return [];
    const out: GoalSection[] = [];
    for (const item of parsed) {
      const row = item as Partial<GoalSection>;
      if (!row || typeof row.title !== "string") continue;
      out.push({
        id: typeof row.id === "string" ? row.id : makeRowId(),
        title: row.title,
        content: typeof row.content === "string" ? row.content : "",
      });
    }
    return out.length ? out : defaultGoalSections();
  } catch {
    return defaultGoalSections();
  }
}

export function saveGoals(sections: GoalSection[]) {
  debounceLocalStorage(GOALS_STORAGE_KEY, sections);
}

export function normalizeReviewHeaders(raw: unknown): [string, string, string, string, string] {
  const d = [...DEFAULT_REVIEW_HEADERS] as [string, string, string, string, string];
  if (!Array.isArray(raw)) return d;
  return [
    typeof raw[0] === "string" ? raw[0] : d[0],
    typeof raw[1] === "string" ? raw[1] : d[1],
    typeof raw[2] === "string" ? raw[2] : d[2],
    typeof raw[3] === "string" ? raw[3] : d[3],
    typeof raw[4] === "string" ? raw[4] : d[4],
  ];
}

export function normalizeReviewRow(o: unknown, newId: () => string): ReviewTableRow | null {
  if (!o || typeof o !== "object") return null;
  const r = o as Record<string, unknown>;
  const id = typeof r.id === "string" && r.id ? r.id : newId();
  return {
    id,
    cycleLabel: typeof r.cycleLabel === "string" ? r.cycleLabel : "",
    managerStrengths: typeof r.managerStrengths === "string" ? r.managerStrengths : "",
    managerOpportunity: typeof r.managerOpportunity === "string" ? r.managerOpportunity : "",
    personalStrengths: typeof r.personalStrengths === "string" ? r.personalStrengths : "",
    personalOpportunity: typeof r.personalOpportunity === "string" ? r.personalOpportunity : "",
  };
}

export function defaultReviewsState(): ReviewsTableState {
  return {
    headers: [...DEFAULT_REVIEW_HEADERS] as [string, string, string, string, string],
    rows: [],
  };
}

export function loadReviews(): ReviewsTableState {
  try {
    const raw = localStorage.getItem(REVIEWS_STORAGE_KEY);
    if (!raw) return defaultReviewsState();
    const parsed = JSON.parse(raw) as { headers?: unknown; rows?: unknown };
    const headers = normalizeReviewHeaders(parsed.headers);
    const rows: ReviewTableRow[] = [];
    if (Array.isArray(parsed.rows)) {
      for (const item of parsed.rows) {
        const row = normalizeReviewRow(item, makeRowId);
        if (row) rows.push(row);
      }
    }
    return { headers, rows };
  } catch {
    return defaultReviewsState();
  }
}

export function saveReviews(state: ReviewsTableState) {
  debounceLocalStorage(REVIEWS_STORAGE_KEY, state);
}

export function isTrackerActive(status: TrackerStatus): boolean {
  return status === "Complete" || status === "Coming Up";
}

export function isLongWeekendHoliday(dateIso: string): boolean {
  const d = parseIsoDateLocal(dateIso);
  if (!d) return false;
  const day = d.getDay();
  return day === 1 || day === 5; // Monday or Friday
}

type TrackerOverride = {
  status: TaskStatus;
  label: string;
  sourceType: "holiday" | "pto" | "conference" | "trip";
  sourceId: string;
};

type OfficeTripBanner = {
  label: string;
  sourceId: string;
};

export function buildTrackerOverrides(tracker: TrackerData): Map<string, TrackerOverride> {
  const out = new Map<string, TrackerOverride>();
  for (const row of tracker.public_holidays) {
    if (!isTrackerActive(row.status)) continue;
    const label = row.name || SPECIAL_LABELS.holiday;
    out.set(row.date, {
      status: "holiday",
      label: isLongWeekendHoliday(row.date) ? `${label} · Long Weekend` : label,
      sourceType: "holiday",
      sourceId: row.id,
    });
  }
  for (const row of tracker.pto) {
    if (!isTrackerActive(row.status)) continue;
    eachDateInclusive(row.startDate, row.endDate, (d) => {
      out.set(toIsoDate(d), {
        status: "pto",
        label: row.description ? `PTO · ${row.description}` : SPECIAL_LABELS.pto,
        sourceType: "pto",
        sourceId: row.id,
      });
    });
  }
  for (const row of tracker.conferences) {
    if (!isTrackerActive(row.status) && row.activity !== "Booked") continue;
    eachDateInclusive(row.startDate, row.endDate, (d) => {
      out.set(toIsoDate(d), {
        status: "offsite",
        label: row.eventName || SPECIAL_LABELS.offsite,
        sourceType: "conference",
        sourceId: row.id,
      });
    });
  }
  return out;
}

export function buildOfficeTripBanners(tracker: TrackerData): Map<string, OfficeTripBanner> {
  const out = new Map<string, OfficeTripBanner>();
  for (const row of tracker.office_trips) {
    if (!isTrackerActive(row.status) && row.activity !== "Booked") continue;
    eachDateInclusive(row.startDate, row.endDate, (d) => {
      out.set(toIsoDate(d), {
        label: row.tripName || "Office Trip",
        sourceId: row.id,
      });
    });
  }
  return out;
}

export function getEntry(
  manifest: TaskManifest,
  monday: Date,
  day: DayName,
): DayEntry {
  const wk = weekKey(monday);
  return monthEntryFor(manifest, monday).daily_logs[wk]?.[day] ?? { status: "work", planned: "", did: "" };
}

export function setEntry(
  manifest: TaskManifest,
  monday: Date,
  day: DayName,
  entry: DayEntry,
): TaskManifest {
  const year = String(monday.getFullYear());
  const month = monthName(monday);
  const wk = weekKey(monday);
  const yearEntry = getYearEntry(manifest, year);
  const monthEntry = yearEntry[month] ?? makeEmptyMonthEntry();
  return {
    ...manifest,
    [year]: {
      ...yearEntry,
      [month]: {
        ...monthEntry,
        daily_logs: {
          ...monthEntry.daily_logs,
          [wk]: {
            ...(monthEntry.daily_logs[wk] ?? {}),
            [day]: entry,
          },
        },
      },
    },
  };
}

export function setWeeklyReview(manifest: TaskManifest, monday: Date, content: string): TaskManifest {
  const year = String(monday.getFullYear());
  const month = monthName(monday);
  const wk = weekKey(monday);
  const yearEntry = getYearEntry(manifest, year);
  const monthEntry = yearEntry[month] ?? makeEmptyMonthEntry();
  return {
    ...manifest,
    [year]: {
      ...yearEntry,
      [month]: {
        ...monthEntry,
        weekly_reviews: {
          ...monthEntry.weekly_reviews,
          [wk]: { content },
        },
      },
    },
  };
}

export function setMonthlyReview(
  manifest: TaskManifest,
  monday: Date,
  patch: { content?: string; achievements?: string },
  dateCompleted: string,
): TaskManifest {
  const year = String(monday.getFullYear());
  const month = monthName(monday);
  const yearEntry = getYearEntry(manifest, year);
  const monthEntry = yearEntry[month] ?? makeEmptyMonthEntry();
  return {
    ...manifest,
    [year]: {
      ...yearEntry,
      [month]: {
        ...monthEntry,
        monthly_review: {
          ...monthEntry.monthly_review,
          ...(patch.content !== undefined ? { content: patch.content } : {}),
          ...(patch.achievements !== undefined ? { achievements: patch.achievements } : {}),
          date_completed: dateCompleted,
        },
      },
    },
  };
}

export function matchesTemplateOnDate(template: PlanTemplate, date: Date): boolean {
  if (!template.enabled) return false;
  const targetDate = startOfDay(date);
  const parsed = parseIsoDateLocal(template.startDate);
  if (!parsed) return false;
  const start = startOfDay(parsed);
  if (targetDate.getTime() < start.getTime()) return false;
  const recurrenceDay = template.recurrenceDay ?? (dayNameFromDate(start) ?? "Monday");

  if (template.cadence === "daily") return true;
  if (template.cadence === "weekly") return dayNameFromDate(targetDate) === recurrenceDay;
  if (template.cadence === "monthly") {
    if (dayNameFromDate(targetDate) !== recurrenceDay) return false;
    const anchor = nextWeekdayOnOrAfter(start, recurrenceDay);
    return weekdayOccurrenceInMonth(targetDate) === weekdayOccurrenceInMonth(anchor);
  }

  const anchor = nextWeekdayOnOrAfter(start, recurrenceDay);
  if (dayNameFromDate(targetDate) !== recurrenceDay) return false;
  const deltaDays = Math.floor((targetDate.getTime() - anchor.getTime()) / 86400000);
  if (deltaDays < 0) return false;
  const interval = Math.max(1, Math.floor(template.intervalDays || 1));
  return deltaDays % interval === 0;
}

export function applyTemplatesToFutureRange(
  manifest: TaskManifest,
  templates: PlanTemplate[],
  startDate: Date,
  days: number,
): { manifest: TaskManifest; changed: boolean } {
  if (!templates.some((t) => t.enabled)) return { manifest, changed: false };
  let updated = manifest;
  let changed = false;
  const start = startOfDay(startDate);
  for (let i = 0; i <= days; i++) {
    const targetDate = addDays(start, i);
    const dayName = dayNameFromDate(targetDate);
    if (!dayName) continue;
    const monday = mondayForDate(targetDate);
    const current = getEntry(updated, monday, dayName);
    if (current.status !== "work") continue;
    if ((current.planned ?? "").trim() !== "") continue;
    const matches = matchingTemplatesForDate(targetDate, templates);
    if (!matches.length) continue;
    const autoPlan = matches.map((t) => t.content.trim()).join("\n");
    updated = setEntry(updated, monday, dayName, {
      ...current,
      planned: autoPlan,
      status: "work",
      label: undefined,
      plannedAutoGenerated: true,
      plannedTemplateIds: matches.map((t) => t.id),
    });
    changed = true;
  }
  return { manifest: updated, changed };
}

export function removeTemplateFutureOccurrences(
  manifest: TaskManifest,
  templateId: string,
  cutoffDate: Date,
  oldTemplates: PlanTemplate[],
  newTemplates: PlanTemplate[],
): { manifest: TaskManifest; changed: boolean } {
  const cutoff = startOfDay(cutoffDate).getTime();
  let updated = manifest;
  let changed = false;

  for (const year of Object.keys(manifest)) {
    const yearNum = Number(year);
    if (!Number.isFinite(yearNum)) continue;
    const yearEntry = getYearEntry(manifest, year);
    for (const [month, monthEntry] of Object.entries(yearEntry)) {
      const monthIdx = MONTH_INDEX[month];
      if (monthIdx === undefined) continue;
      for (const wk of Object.keys(monthEntry.daily_logs)) {
        const monday = parseWeekStartFromKey(yearNum, monthIdx, wk);
        if (!monday) continue;
        for (const day of DAY_NAMES) {
          const current = monthEntryFor(updated, monday).daily_logs[wk]?.[day];
          if (!current) continue;
          const targetDate = dayDate(monday, day);
          if (targetDate.getTime() <= cutoff) continue;
          const currentPlanned = (current.planned ?? "").trim();
          if (!currentPlanned) continue;

          const oldMatches = matchingTemplatesForDate(targetDate, oldTemplates);
          const newMatches = matchingTemplatesForDate(targetDate, newTemplates);
          const oldPlan = oldMatches.map((t) => t.content.trim()).join("\n");
          const nextPlan = newMatches.map((t) => t.content.trim()).join("\n");
          const hadTemplateByMeta =
            current.plannedAutoGenerated === true &&
            (current.plannedTemplateIds ?? []).includes(templateId);
          // Backward compatibility for previously generated rows without provenance metadata.
          const hadTemplateByComputed =
            oldMatches.some((t) => t.id === templateId) && currentPlanned === oldPlan;
          if (!hadTemplateByMeta && !hadTemplateByComputed) continue;

          const nextTemplateIds = nextPlan.length > 0 ? newMatches.map((t) => t.id) : undefined;
          const nextAuto = nextPlan.length > 0;
          const shouldWrite =
            currentPlanned !== nextPlan ||
            current.plannedAutoGenerated !== nextAuto ||
            JSON.stringify(current.plannedTemplateIds ?? []) !== JSON.stringify(nextTemplateIds ?? []);
          if (!shouldWrite) continue;
          updated = setEntry(updated, monday, day, {
            ...current,
            planned: nextPlan,
            status: "work",
            label: undefined,
            plannedAutoGenerated: nextAuto,
            plannedTemplateIds: nextTemplateIds,
          });
          changed = true;
        }
      }
    }
  }

  return { manifest: updated, changed };
}

export function applyTrackerOverrides(manifest: TaskManifest): { manifest: TaskManifest; changed: boolean } {
  const tracker = getTracker(manifest);
  const overrides = buildTrackerOverrides(tracker);
  const officeTripBanners = buildOfficeTripBanners(tracker);
  let updated = manifest;
  let changed = false;

  // Remove stale tracker-controlled states if the event no longer exists.
  for (const year of Object.keys(manifest)) {
    const yearNum = Number(year);
    if (!Number.isFinite(yearNum)) continue;
    const yearEntry = getYearEntry(manifest, year);
    for (const [month, monthEntry] of Object.entries(yearEntry)) {
      const monthIdx = MONTH_INDEX[month];
      if (monthIdx === undefined) continue;
      for (const wk of Object.keys(monthEntry.daily_logs)) {
        const monday = parseWeekStartFromKey(yearNum, monthIdx, wk);
        if (!monday) continue;
        for (const day of DAY_NAMES) {
          const cell = monthEntryFor(updated, monday).daily_logs[wk]?.[day];
          const d = dayDate(monday, day);
          const key = toIsoDate(d);
          const next = overrides.get(key);
          const nextTrip = officeTripBanners.get(key);
          let nextCell = cell;

          if (nextCell?.trackerSourceType) {
            const keepTrackerState =
              next &&
              next.sourceType === nextCell.trackerSourceType &&
              next.sourceId === nextCell.trackerSourceId;
            if (!keepTrackerState) {
              nextCell = {
                ...nextCell,
                status: "work",
                label: undefined,
                trackerSourceType: undefined,
                trackerSourceId: undefined,
              };
            }
          }

          // Backward compatibility: old office trips previously used hard override status.
          if (nextCell?.trackerSourceType === "trip" && !nextTrip) {
            nextCell = {
              ...nextCell,
              status: "work",
              label: undefined,
              trackerSourceType: undefined,
              trackerSourceId: undefined,
            };
          }

          if (nextCell?.officeTripEventId) {
            const keepBanner = nextTrip && nextTrip.sourceId === nextCell.officeTripEventId;
            if (!keepBanner) {
              nextCell = {
                ...nextCell,
                officeTripBanner: undefined,
                officeTripEventId: undefined,
              };
            }
          }

          if (nextCell !== cell && nextCell) {
            updated = setEntry(updated, monday, day, nextCell);
            changed = true;
          }
        }
      }
    }
  }

  // Apply active overrides from tracker.
  for (const [dateIso, event] of overrides.entries()) {
    const parsed = parseIsoDateLocal(dateIso);
    if (!parsed) continue;
    const d = startOfDay(parsed);
    const day = dayNameFromDate(d);
    if (!day) continue; // planner grid is weekdays only
    const monday = mondayForDate(d);
    const cell = getEntry(updated, monday, day);
    if (
      cell.status === event.status &&
      cell.label === event.label &&
      cell.trackerSourceType === event.sourceType &&
      cell.trackerSourceId === event.sourceId
    ) {
      continue;
    }
    updated = setEntry(updated, monday, day, {
      ...cell,
      status: event.status,
      label: event.label,
      trackerSourceType: event.sourceType,
      trackerSourceId: event.sourceId,
    });
    changed = true;
  }

  // Apply office trip banners without overriding day status/content blocks.
  for (const [dateIso, banner] of officeTripBanners.entries()) {
    const parsed = parseIsoDateLocal(dateIso);
    if (!parsed) continue;
    const d = startOfDay(parsed);
    const day = dayNameFromDate(d);
    if (!day) continue;
    const monday = mondayForDate(d);
    const cell = getEntry(updated, monday, day);
    if (cell.officeTripBanner === banner.label && cell.officeTripEventId === banner.sourceId) {
      continue;
    }
    updated = setEntry(updated, monday, day, {
      ...cell,
      officeTripBanner: banner.label,
      officeTripEventId: banner.sourceId,
    });
    changed = true;
  }

  return { manifest: updated, changed };
}
