/** Plan template recurrence matching and manifest application. */

import {
  addDays,
  dayDate,
  dayNameFromDate,
  mondayForDate,
  nextWeekdayOnOrAfter,
  parseIsoDateLocal,
  parseWeekStartFromKey,
  startOfDay,
  weekdayOccurrenceInMonth,
} from "./plannerDates";
import { getEntry, monthEntryFor, setEntry } from "./plannerManifestOps";
import {
  DAY_NAMES,
  MONTH_INDEX,
  type PlanTemplate,
  type TaskManifest,
} from "./plannerTypes";

export function recurrenceLabel(t: PlanTemplate): string {
  if (t.cadence === "daily") return "daily";
  if (t.cadence === "weekly") return `every ${t.recurrenceDay}`;
  if (t.cadence === "monthly") return `monthly on ${t.recurrenceDay}`;
  return `every ${t.intervalDays} days on ${t.recurrenceDay}`;
}

export function matchingTemplatesForDate(date: Date, templates: PlanTemplate[]): PlanTemplate[] {
  return templates.filter((t) => matchesTemplateOnDate(t, date) && t.content.trim().length > 0);
}

export function matchesTemplateOnDate(template: PlanTemplate, date: Date): boolean {
  if (!template.enabled) return false;
  const targetDate = startOfDay(date);
  const parsed = parseIsoDateLocal(template.startDate);
  if (!parsed) return false;
  const start = startOfDay(parsed);
  if (targetDate.getTime() < start.getTime()) return false;
  const recurrenceDay = template.recurrenceDay ?? (dayNameFromDate(start) ?? "Monday");

  if (template.cadence === "daily") return true;
  if (template.cadence === "weekly") return dayNameFromDate(targetDate) === recurrenceDay;
  if (template.cadence === "monthly") {
    if (dayNameFromDate(targetDate) !== recurrenceDay) return false;
    const anchor = nextWeekdayOnOrAfter(start, recurrenceDay);
    return weekdayOccurrenceInMonth(targetDate) === weekdayOccurrenceInMonth(anchor);
  }

  const anchor = nextWeekdayOnOrAfter(start, recurrenceDay);
  if (dayNameFromDate(targetDate) !== recurrenceDay) return false;
  const deltaDays = Math.floor((targetDate.getTime() - anchor.getTime()) / 86400000);
  if (deltaDays < 0) return false;
  const interval = Math.max(1, Math.floor(template.intervalDays || 1));
  return deltaDays % interval === 0;
}

export function applyTemplatesToFutureRange(
  manifest: TaskManifest,
  templates: PlanTemplate[],
  startDate: Date,
  days: number,
): { manifest: TaskManifest; changed: boolean } {
  if (!templates.some((t) => t.enabled)) return { manifest, changed: false };
  let updated = manifest;
  let changed = false;
  const start = startOfDay(startDate);
  for (let i = 0; i <= days; i++) {
    const targetDate = addDays(start, i);
    const dayName = dayNameFromDate(targetDate);
    if (!dayName) continue;
    const monday = mondayForDate(targetDate);
    const current = getEntry(updated, monday, dayName);
    if (current.status !== "work") continue;
    if ((current.planned ?? "").trim() !== "") continue;
    const matches = matchingTemplatesForDate(targetDate, templates);
    if (!matches.length) continue;
    const autoPlan = matches.map((t) => t.content.trim()).join("\n");
    updated = setEntry(updated, monday, dayName, {
      ...current,
      planned: autoPlan,
      status: "work",
      label: undefined,
      plannedAutoGenerated: true,
      plannedTemplateIds: matches.map((t) => t.id),
    });
    changed = true;
  }
  return { manifest: updated, changed };
}

export function removeTemplateFutureOccurrences(
  manifest: TaskManifest,
  templateId: string,
  cutoffDate: Date,
  oldTemplates: PlanTemplate[],
  newTemplates: PlanTemplate[],
): { manifest: TaskManifest; changed: boolean } {
  const cutoff = startOfDay(cutoffDate).getTime();
  let updated = manifest;
  let changed = false;

  for (const year of Object.keys(manifest)) {
    const yearNum = Number(year);
    if (!Number.isFinite(yearNum)) continue;
    const yearEntry = manifest[year];
    if (!yearEntry || typeof yearEntry !== "object" || Array.isArray(yearEntry) || year === "tracker") continue;
    if ("public_holidays" in yearEntry) continue;
    for (const [month, monthEntry] of Object.entries(yearEntry)) {
      const monthIdx = MONTH_INDEX[month];
      if (monthIdx === undefined) continue;
      for (const wk of Object.keys(monthEntry.daily_logs)) {
        const monday = parseWeekStartFromKey(yearNum, monthIdx, wk);
        if (!monday) continue;
        for (const day of DAY_NAMES) {
          const current = monthEntryFor(updated, monday).daily_logs[wk]?.[day];
          if (!current) continue;
          const targetDate = dayDate(monday, day);
          if (targetDate.getTime() <= cutoff) continue;
          const currentPlanned = (current.planned ?? "").trim();
          if (!currentPlanned) continue;

          const oldMatches = matchingTemplatesForDate(targetDate, oldTemplates);
          const newMatches = matchingTemplatesForDate(targetDate, newTemplates);
          const oldPlan = oldMatches.map((t) => t.content.trim()).join("\n");
          const nextPlan = newMatches.map((t) => t.content.trim()).join("\n");
          const hadTemplateByMeta =
            current.plannedAutoGenerated === true &&
            (current.plannedTemplateIds ?? []).includes(templateId);
          // Backward compatibility for previously generated rows without provenance metadata.
          const hadTemplateByComputed =
            oldMatches.some((t) => t.id === templateId) && currentPlanned === oldPlan;
          if (!hadTemplateByMeta && !hadTemplateByComputed) continue;

          const nextTemplateIds = nextPlan.length > 0 ? newMatches.map((t) => t.id) : undefined;
          const nextAuto = nextPlan.length > 0;
          const shouldWrite =
            currentPlanned !== nextPlan ||
            current.plannedAutoGenerated !== nextAuto ||
            JSON.stringify(current.plannedTemplateIds ?? []) !== JSON.stringify(nextTemplateIds ?? []);
          if (!shouldWrite) continue;
          updated = setEntry(updated, monday, day, {
            ...current,
            planned: nextPlan,
            status: "work",
            label: undefined,
            plannedAutoGenerated: nextAuto,
            plannedTemplateIds: nextTemplateIds,
          });
          changed = true;
        }
      }
    }
  }

  return { manifest: updated, changed };
}
