/** Planner domain types, constants, and factory helpers. */

export type DayName = "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday";
export type TaskStatus = "work" | "holiday" | "sick" | "pto" | "personal" | "offsite";
export type PlannerTab = "daily" | "weekly" | "monthly" | "templates" | "tracker" | "goals" | "reviews";
export type TemplateCadence = "daily" | "weekly" | "monthly" | "interval";
export type TrackerStatus = "Complete" | "Coming Up" | "Pending";

export type DayEntry = {
  status: TaskStatus;
  planned?: string;
  did?: string;
  label?: string;
  plannedAutoGenerated?: boolean;
  plannedTemplateIds?: string[];
  trackerSourceType?: "holiday" | "pto" | "conference" | "trip";
  trackerSourceId?: string;
  officeTripBanner?: string;
  officeTripEventId?: string;
};

export type WeekEntry = Partial<Record<DayName, DayEntry>>;
export type WeeklyReviewEntry = { content: string };
export type MonthlyReviewEntry = { content: string; achievements?: string; date_completed?: string };
export type MonthEntry = {
  daily_logs: Record<string, WeekEntry>;
  weekly_reviews: Record<string, WeeklyReviewEntry>;
  monthly_review: MonthlyReviewEntry;
};
export type YearEntry = Record<string, MonthEntry>;
export type PublicHolidayEntry = {
  id: string;
  name: string;
  date: string;
  status: TrackerStatus;
  notes: string;
};
export type PtoEntry = {
  id: string;
  description: string;
  startDate: string;
  endDate: string;
  daysTotal: number;
  daysTaken: number;
  status: TrackerStatus;
  notes: string;
};
export type ConferenceEntry = {
  id: string;
  eventName: string;
  startDate: string;
  endDate: string;
  location: string;
  activity: "Booked" | "Pending";
  status: TrackerStatus;
  notes: string;
};
export type OfficeTripEntry = {
  id: string;
  tripName: string;
  startDate: string;
  endDate: string;
  location: string;
  activity: "Booked" | "Pending";
  status: TrackerStatus;
  notes: string;
};
export type TrackerData = {
  public_holidays: PublicHolidayEntry[];
  pto: PtoEntry[];
  conferences: ConferenceEntry[];
  office_trips: OfficeTripEntry[];
  pto_stats: {
    total_allocation: number;
  };
};
export type TaskManifest = {
  tracker?: TrackerData;
  [year: string]: YearEntry | TrackerData | undefined;
};
export type PlanTemplate = {
  id: string;
  name: string;
  cadence: TemplateCadence;
  intervalDays: number;
  startDate: string;
  content: string;
  enabled: boolean;
  recurrenceDay: DayName;
};
export type PlannerLayoutTemplates = {
  dailyPrimaryLabel: string;
  dailySecondaryEnabled: boolean;
  dailySecondaryLabel: string;
  weeklyLeftHeader: string;
  weeklyRightHeader: string;
  weeklyDefaultContent: string;
  monthlyLeftHeader: string;
  monthlyRightHeader: string;
  monthlyPrompts: string[];
};

export type GoalSection = {
  id: string;
  title: string;
  content: string;
};

export type ReviewTableRow = {
  id: string;
  cycleLabel: string;
  managerStrengths: string;
  managerOpportunity: string;
  personalStrengths: string;
  personalOpportunity: string;
};

export type ReviewsTableState = {
  headers: [string, string, string, string, string];
  rows: ReviewTableRow[];
};

export const TEMPLATE_FUTURE_HORIZON_DAYS = 365;
export const DAY_NAMES: DayName[] = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];

export const MONTH_INDEX: Record<string, number> = {
  January: 0,
  February: 1,
  March: 2,
  April: 3,
  May: 4,
  June: 5,
  July: 6,
  August: 7,
  September: 8,
  October: 9,
  November: 10,
  December: 11,
};

export const DAY_INDEX: Record<DayName, number> = {
  Monday: 0,
  Tuesday: 1,
  Wednesday: 2,
  Thursday: 3,
  Friday: 4,
};

export const MONTHLY_PROMPTS = [
  "What went well?",
  "What went badly?",
  "What did you struggle with?",
  "What did you learn?",
  "Action points from the previous month - what am I going to do differently / focus on.",
];

export const HOLIDAY_COUNTRIES: Array<{ code: string; label: string }> = [
  { code: "US", label: "United States" },
  { code: "CA", label: "Canada" },
  { code: "GB", label: "United Kingdom" },
  { code: "AU", label: "Australia" },
  { code: "DE", label: "Germany" },
  { code: "FR", label: "France" },
  { code: "IN", label: "India" },
  { code: "JP", label: "Japan" },
];

export const HOLIDAY_REGIONS: Record<string, Array<{ code: string; label: string }>> = {
  US: [
    { code: "US-CA", label: "California" },
    { code: "US-NY", label: "New York" },
    { code: "US-TX", label: "Texas" },
    { code: "US-WA", label: "Washington" },
  ],
  CA: [
    { code: "CA-ON", label: "Ontario" },
    { code: "CA-QC", label: "Quebec" },
    { code: "CA-BC", label: "British Columbia" },
    { code: "CA-AB", label: "Alberta" },
  ],
  AU: [
    { code: "AU-NSW", label: "New South Wales" },
    { code: "AU-VIC", label: "Victoria" },
    { code: "AU-QLD", label: "Queensland" },
    { code: "AU-WA", label: "Western Australia" },
  ],
  DE: [
    { code: "DE-BY", label: "Bavaria" },
    { code: "DE-BW", label: "Baden-Wuerttemberg" },
    { code: "DE-NW", label: "North Rhine-Westphalia" },
  ],
};

export const WEEKLY_TEMPLATE = "- \n\n**Action Points:** ";

export const DEFAULT_LAYOUT_TEMPLATES: PlannerLayoutTemplates = {
  dailyPrimaryLabel: "What do I want to do",
  dailySecondaryEnabled: true,
  dailySecondaryLabel: "What did I do",
  weeklyLeftHeader: "Encountered Weekly",
  weeklyRightHeader: "Main Points & Issues Encountered",
  weeklyDefaultContent: WEEKLY_TEMPLATE,
  monthlyLeftHeader: "Monthly Review",
  monthlyRightHeader: "Issues Encountered",
  monthlyPrompts: [...MONTHLY_PROMPTS],
};

export const SPECIAL_LABELS: Record<Exclude<TaskStatus, "work">, string> = {
  holiday: "Public Holiday",
  sick: "Sick Day",
  pto: "PTO",
  personal: "Personal",
  offsite: "Off-site / Conference",
};

export const PLANNER_PURPLE_HEADER =
  "flex min-h-[2.5rem] items-center justify-center rounded-md bg-[#7F00FF] px-2 py-1.5 text-center text-[11px] font-semibold text-white";

export function makeRowId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

export function makeMonthlyTemplateContent(prompts: string[] = MONTHLY_PROMPTS): string {
  return prompts.map((prompt) => `- ${prompt}\n`).join("\n");
}

export function makeEmptyMonthEntry(): MonthEntry {
  return {
    daily_logs: {},
    weekly_reviews: {},
    monthly_review: { content: "", achievements: "" },
  };
}

export function makeEmptyTracker(): TrackerData {
  return {
    public_holidays: [],
    pto: [],
    conferences: [],
    office_trips: [],
    pto_stats: { total_allocation: 26 },
  };
}
