import { useEffect, useState } from "react";
import {
  type DayName,
  type PlanTemplate,
  type TaskManifest,
  type TemplateCadence,
  DAY_NAMES,
  TEMPLATE_FUTURE_HORIZON_DAYS,
  applyTemplatesToFutureRange,
  getEntry,
  loadTemplates,
  matchingTemplatesForDate,
  removeTemplateFutureOccurrences,
  saveManifest,
  saveTemplates,
  setEntry,
  dayDate,
  parseIsoDateLocal,
  toIsoDate,
} from "@/planner/plannerStorage";

export interface PendingTemplateAction {
  templateId: string;
  action: "disable" | "delete";
  cutoffDate: string;
}

export interface UsePlanTemplatesOptions {
  plannerReady: boolean;
  plannerReloadKey: number;
  hydrationComplete: boolean;
  today: Date;
  manifest: TaskManifest;
  setManifest: React.Dispatch<React.SetStateAction<TaskManifest>>;
  visibleWeeks: Date[];
}

export function usePlanTemplates({
  plannerReady,
  plannerReloadKey,
  hydrationComplete,
  today,
  manifest,
  setManifest,
  visibleWeeks,
}: UsePlanTemplatesOptions) {
  const [templates, setTemplates] = useState<PlanTemplate[]>([]);
  const [templateName, setTemplateName] = useState("");
  const [templateCadence, setTemplateCadence] = useState<TemplateCadence>("daily");
  const [templateIntervalDaysInput, setTemplateIntervalDaysInput] = useState("14");
  const [templateStartDate, setTemplateStartDate] = useState(() => toIsoDate(today));
  const [templateContent, setTemplateContent] = useState("- ");
  const [templateRecurrenceDay, setTemplateRecurrenceDay] = useState<DayName>("Monday");
  const [editingTemplateId, setEditingTemplateId] = useState<string | null>(null);
  const [editTemplateName, setEditTemplateName] = useState("");
  const [editTemplateCadence, setEditTemplateCadence] = useState<TemplateCadence>("daily");
  const [editTemplateIntervalDaysInput, setEditTemplateIntervalDaysInput] = useState("14");
  const [editTemplateStartDate, setEditTemplateStartDate] = useState(() => toIsoDate(today));
  const [editTemplateContent, setEditTemplateContent] = useState("");
  const [editTemplateRecurrenceDay, setEditTemplateRecurrenceDay] = useState<DayName>("Monday");
  const [pendingTemplateAction, setPendingTemplateAction] = useState<PendingTemplateAction | null>(null);

  useEffect(() => {
    if (!plannerReady) {
      setTemplates([]);
      return;
    }
    setTemplates(loadTemplates());
  }, [plannerReady, plannerReloadKey]);

  useEffect(() => {
    if (!hydrationComplete) return;
    saveTemplates(templates);
  }, [templates, hydrationComplete]);

  useEffect(() => {
    setManifest((prev) => {
      const result = applyTemplatesToFutureRange(prev, templates, today, TEMPLATE_FUTURE_HORIZON_DAYS);
      if (!result.changed) return prev;
      saveManifest(result.manifest);
      return result.manifest;
    });
  }, [templates, today, setManifest]);

  useEffect(() => {
    if (!templates.some((t) => t.enabled)) return;
    setManifest((prev) => {
      let updated = prev;
      let changed = false;
      for (const monday of visibleWeeks) {
        for (const day of DAY_NAMES) {
          const current = getEntry(updated, monday, day);
          if (current.status !== "work") continue;
          if ((current.planned ?? "").trim() !== "") continue;
          const targetDate = dayDate(monday, day);
          const matches = matchingTemplatesForDate(targetDate, templates);
          if (!matches.length) continue;
          const autoPlan = matches.map((t) => t.content.trim()).join("\n");
          updated = setEntry(updated, monday, day, {
            ...current,
            planned: autoPlan,
            status: "work",
            label: undefined,
            plannedAutoGenerated: true,
            plannedTemplateIds: matches.map((t) => t.id),
          });
          changed = true;
        }
      }
      if (!changed) return prev;
      saveManifest(updated);
      return updated;
    });
  }, [templates, visibleWeeks, setManifest]);

  const addTemplate = () => {
    const normalizedContent = templateContent.trim();
    if (!normalizedContent) return;
    const intervalDays = Math.max(1, Math.floor(Number(templateIntervalDaysInput) || 1));
    const next: PlanTemplate = {
      id: `${Date.now()}-${Math.random().toString(36).slice(2)}`,
      name: templateName.trim() || `Template ${templates.length + 1}`,
      cadence: templateCadence,
      intervalDays,
      startDate: templateStartDate,
      content: normalizedContent,
      enabled: true,
      recurrenceDay: templateRecurrenceDay,
    };
    setTemplates((prev) => [...prev, next]);
    setTemplateName("");
    setTemplateContent("- ");
    setTemplateIntervalDaysInput("14");
  };

  const toggleTemplate = (id: string) => {
    const target = templates.find((t) => t.id === id);
    if (!target) return;
    if (!target.enabled) {
      setTemplates((prev) => prev.map((t) => (t.id === id ? { ...t, enabled: true } : t)));
      return;
    }
    setPendingTemplateAction({
      templateId: id,
      action: "disable",
      cutoffDate: toIsoDate(today),
    });
  };

  const deleteTemplate = (id: string) => {
    setPendingTemplateAction({
      templateId: id,
      action: "delete",
      cutoffDate: toIsoDate(today),
    });
  };

  const startEditTemplate = (template: PlanTemplate) => {
    setEditingTemplateId(template.id);
    setEditTemplateName(template.name);
    setEditTemplateCadence(template.cadence);
    setEditTemplateIntervalDaysInput(String(template.intervalDays));
    setEditTemplateStartDate(template.startDate);
    setEditTemplateContent(template.content);
    setEditTemplateRecurrenceDay(template.recurrenceDay);
  };

  const cancelEditTemplate = () => {
    setEditingTemplateId(null);
  };

  const cancelTemplateAction = () => {
    setPendingTemplateAction(null);
  };

  const confirmTemplateAction = () => {
    if (!pendingTemplateAction) return;
    const cutoff = parseIsoDateLocal(pendingTemplateAction.cutoffDate);
    if (!cutoff) return;
    if (pendingTemplateAction.action === "disable") {
      const updatedTemplates = templates.map((t) =>
        t.id === pendingTemplateAction.templateId ? { ...t, enabled: false } : t,
      );
      const pruned = removeTemplateFutureOccurrences(
        manifest,
        pendingTemplateAction.templateId,
        cutoff,
        templates,
        updatedTemplates,
      );
      if (pruned.changed) {
        saveManifest(pruned.manifest);
        setManifest(pruned.manifest);
      }
      setTemplates(updatedTemplates);
      setPendingTemplateAction(null);
      return;
    }

    const updatedTemplates = templates.filter((t) => t.id !== pendingTemplateAction.templateId);
    const pruned = removeTemplateFutureOccurrences(
      manifest,
      pendingTemplateAction.templateId,
      cutoff,
      templates,
      updatedTemplates,
    );
    if (pruned.changed) {
      saveManifest(pruned.manifest);
      setManifest(pruned.manifest);
    }
    setTemplates(updatedTemplates);
    if (editingTemplateId === pendingTemplateAction.templateId) {
      setEditingTemplateId(null);
    }
    setPendingTemplateAction(null);
  };

  const saveTemplateEdits = () => {
    if (!editingTemplateId) return;
    const normalizedContent = editTemplateContent.trim();
    if (!normalizedContent) return;
    const intervalDays = Math.max(1, Math.floor(Number(editTemplateIntervalDaysInput) || 1));
    setTemplates((prev) =>
      prev.map((t) =>
        t.id === editingTemplateId
          ? {
              ...t,
              name: editTemplateName.trim() || t.name,
              cadence: editTemplateCadence,
              intervalDays,
              startDate: editTemplateStartDate,
              content: normalizedContent,
              recurrenceDay: editTemplateRecurrenceDay,
            }
          : t,
      ),
    );
    setEditingTemplateId(null);
  };

  return {
    templates,
    templateName,
    setTemplateName,
    templateCadence,
    setTemplateCadence,
    templateIntervalDaysInput,
    setTemplateIntervalDaysInput,
    templateStartDate,
    setTemplateStartDate,
    templateContent,
    setTemplateContent,
    templateRecurrenceDay,
    setTemplateRecurrenceDay,
    editingTemplateId,
    editTemplateName,
    setEditTemplateName,
    editTemplateCadence,
    setEditTemplateCadence,
    editTemplateIntervalDaysInput,
    setEditTemplateIntervalDaysInput,
    editTemplateStartDate,
    setEditTemplateStartDate,
    editTemplateContent,
    setEditTemplateContent,
    editTemplateRecurrenceDay,
    setEditTemplateRecurrenceDay,
    pendingTemplateAction,
    setPendingTemplateAction,
    addTemplate,
    toggleTemplate,
    deleteTemplate,
    startEditTemplate,
    cancelEditTemplate,
    cancelTemplateAction,
    confirmTemplateAction,
    saveTemplateEdits,
  };
}
